### ISSUE TITLE
About Exercise 2.29

### ISSUE THREAD

**Issue by husnda** [pezy/CppPrimer#136]
### Exercise

 2.29
Uing the variables in the previous exercise, which of the following assignments are legal? Explain why.
reference: Exercise 2.28
Explain the following definitions. Identify any that are illegal.
int i, *const cp;       // illegal, cp must initialize.
int *p1, *const p2;     // illegal, p2 must initialize.
const int ic, &r = ic;  // illegal, ic must initialize.
const int *const p3;    // illegal, p3 must initialize.
const int *p;           // legal. a pointer to const int.

### Question or Bug

p1 = p3;    // illegal. p3 is a pointer to const int.

why can't const pointer assign to regular pointer?

I've checked _https://stackoverflow.com/questions/3316562/const-pointer-assign-to-a-pointer_
it says "_You can always assign constant to variable i.e. const pointer to non-const pointer_"

### Your enviroment information

- **System**: win10 :
- **Compiler version/IDE**:vs2017 community

**Comment by pezy** [comment]
> why can't const pointer assign to regular pointer?

because the type is incompatible.

> You can always assign constant to variable i.e. const pointer to non-const pointer

**const pointer** to non-const pointer is OK, such as the example in that answer:

```cpp
int * pointer;
int * const const_pointer = &var;

pointer = const_pointer; // OK
```

But return to our exercise, **`p3` is const pointer to const** which is declared as `const int *const p3`.

Thus, `p3` is not only a **const pointer**, but also a **pointer to const**.

Then, you can read the SO's answer more carefully, it said "But you **cannot** cast pointer to const to a pointer to non-const (c)" after your reference, and it also give the example code:

```cpp
int * pointer;
const int * pointer_to_const;
/* c */
pointer = pointer_to_const; // Illegal, casting 'const int*' to 'int*'
```

So, you cannot assign the `p3`(pointer to `const int*`) to `p1`(pointer to `const`).

**Comment by husnda** [comment]
Thank you!
我说中文吧，现在我理解了，造成错误的原因在于pointer to const与const pointer的区别。
我是一个初学者，刚开始我对这个还是理解的，在做完练习查找答案的时候找到不同的版本，首当其冲当然是中文答案，参见https://github.com/huangmingchuan/Cpp_Primer_Answers/blob/master/ch02/README.md 该答案多处与我的理解相出入，因此找寻英文版答案，有幸看到您的答案(包括Mooophy的答案)。这些答案在我思考Exercise2.29时有了分歧，中文版答案在解释illegal时是这样说的“_p1 = p3;    // 不合法, p3 是const指针不能赋值给普通指针_”，另外居然指出练习2.29(d)(e)(f)居然是合法的。。。这让我质疑自己的判断，现在看来中文版的答案真的有不少谬误，现在决定将中文版答案从bookmark里移除。
**我觉得一些规则的正确与否对于初学者真的很重要**，我在中文版repository里也发布了相关issue却没有任何反馈。
真的很感谢您的回答，如果以后还遇到问题向您请教，请不吝赐教。
